# Generated by Django 2.1.2 on 2018-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order_service", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_amount",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(default="devin.mens@sap.com", max_length=64),
        ),
    ]
