# Generated by Django 2.1.2 on 2018-12-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("order_service", "0002_auto_20181204_0044")]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="productId", new_name="productCode"
        )
    ]
