# Generated by Django 2.1.2 on 2018-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order_service", "0003_auto_20181204_0049")]

    operations = [
        migrations.AddField(
            model_name="stocklevel", name="amount", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="product",
            name="productId",
            field=models.IntegerField(unique=True),
        ),
    ]
