# Generated by Django 2.1.2 on 2018-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order_service", "0004_auto_20181204_1346")]

    operations = [
        migrations.AddField(
            model_name="order", name="placed", field=models.BooleanField(default=True)
        )
    ]
