# Generated by Django 2.1.2 on 2018-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order_service", "0007_order_created_at")]

    operations = [
        migrations.AlterField(
            model_name="order", name="created_at", field=models.FloatField()
        )
    ]
